[master]
npx=1
npy=1

[grid]
itot=200
jtot=200
ktot=350

xsize=6400.
ysize=6400.
zsize=4000.

utrans=-8.
vtrans= 0.

swspatialorder=2

[advec]
swadvec=2
cflmax=0.5

[diff]
swdiff=smag2
dnmax=0.3

[thermo]
swbasestate=anelastic
swthermo=moist
pbot=101500.
swupdatebasestate=1

[force]
swlspres=geo
fc=0.376e-4
swls=1
lslist=thl,qt
swwls=mean

#[windfarm]
#swwf=adm
#diameter=198.
#hubheight=119.
#diskmemtime=600
#adresolution=5.
#wfturblocs=BOMEX-IEA10-05x05.txt
#wfturblocformat=xy
#wfyawfile=BOMEX-IEA10-05x05-yaw.txt
#wfstarttime=21600.
#wframptime=300.
#sampletime=10.
#ctprime=1.3333333333333333

[boundary]
mbcbot=noslip
mbctop=freeslip
sbcbot=dirichlet
sbctop=neumann
sbot=0.
stop=0.
sbot[thl]=299.1253
sbot[qt]=0.02245
stop[thl]=0.00365
stop[qt]=1.2e-6
swboundary=surface_bulk

## First estimates derived from the BOMEX target state and fluxes
#bulk_cm=1.024e-3
bulk_cs=0.
#bulk_cs[thl]=2.286e-3
#bulk_cs[qt]=1.090e-3

# Second iteration refined surface parameters
#bulk_cm=1.65119e-3
#bulk_cs[thl]=3.36953e-3
#bulk_cs[qt]=1.48682e-3

# Third iteration refined surface parameters
#bulk_cm=1.978e-3
#bulk_cs[thl]=4.902e-3
#bulk_cs[qt]=1.664e-3

# Fourth iteration refined surface parameters
bulk_cm=2.153e-3
bulk_cs[thl]=6.952e-3
bulk_cs[qt]=1.736e-3

z0m=2.e-4
z0h=2.e-4

[fields]
visc=1.e-5
svisc=1.e-5
#slist=couvreux

rndseed=2
rndamp[thl]=0.1
rndamp[qt]=1.e-4
rndz=300.
rndexp=2.

[buffer]
swbuffer=1
zstart=3500.
sigma=0.00223
beta=2.

#[decay]
#swdecay[couvreux]=exponential
#timescale=600.

[time]
endtime=21600
dt=1.
dtmax=60.
savetime=3600
outputiter=1
adaptivestep=true
starttime=3600
rkorder=3

[stats]
swstats=1
swtendency=1
sampletime=60
masklist=ql,qlcore
#whitelist=qt_1_qt_1, qt_1_w_1
whitelist=thl_1_qt_1,qt_1_thl_1
#blacklist=.*_w,.*_flux

[column]
swcolumn=0
sampletime=60
coordinates[x]=0, 6400
coordinates[y]=6400, 0

[dump]
swdump=0
sampletime=1800
dumplist=u,v,w,qt,ql,thl

[cross]
swcross=0
crosslist=qt,ql,ql_path,w,u
sampletime=300
xz=6400
yz=6400
xy=5,119

