[master]
npx=1
npy=1

[grid]
itot=200
jtot=200
ktot=350

xsize=6400.
ysize=6400.
zsize=4000.

utrans=-8.
vtrans= 0.

swspatialorder=2

[advec]
swadvec=2
cflmax=0.3

[diff]
swdiff=smag2
dnmax=0.3

[thermo]
swbasestate=anelastic
swthermo=moist
pbot=101500.
swupdatebasestate=1

[force]
swlspres=geo
fc=0.376e-4
swls=1
lslist=thl,qt
swwls=mean

#[windfarm]
#swwf=adm
#diameter=198.
#hubheight=119.
#diskmemtime=600
#adresolution=5.
#wfturblocs=BOMEX-IEA10-05x05.txt
#wfturblocformat=xy
#wfyawfile=BOMEX-IEA10-05x05-yaw.txt
#wfstarttime=21600.
#wframptime=300.
#sampletime=10.
#ctprime=1.3333333333333333

#[boundary]
#mbcbot=noslip
#sbcbot=dirichlet
swboundary=surface
#sbot[thl]=297.83
#sbot[qt]=0.02245

#mbctop=freeslip
#sbctop=neumann
#stop[thl]=0.00365
#stop[qt]=1.2e-6

#sbot=0
#stop=0

#z0m=0.0002
#z0h=0.0002





#sbot[couvreux]=1e-5
#stop[couvreux]=0.


# BOUNDARY CONDITIONS FROM RICO
#[boundary]
#mbcbot=noslip
#mbctop=freeslip
#sbcbot=dirichlet
#sbctop=neumann
#sbot=0
#stop=0
#sbot[thl]=298.494255
#stop[thl]=5.86e-3
#sbot[qt]=0.021663
#stop[qt]=-8.11e-7
#swboundary=surface_bulk
#bulk_cm=0.001229
#bulk_cs=0
#bulk_cs[thl]=0.001094
#bulk_cs[qt]=0.001133
#z0m=0.0002
#z0h=0.0002

# DEFAULT BOMEX BOUNDARY CONDITIONS
[boundary]
mbcbot=ustar
mbctop=freeslip
sbcbot=flux
sbctop=neumann
sbot=0
stop=0
sbot[thl]=8.e-3
stop[thl]=0.00365
sbot[qt]=5.2e-5
stop[qt]=1.2e-6
#sbot[couvreux]=1e-5
#stop[couvreux]=0.
swboundary=surface
z0m=0.1
z0h=0.1
ustar=0.28

[fields]
visc=1.e-5
svisc=1.e-5
#slist=couvreux

rndseed=2
rndamp[thl]=0.1
rndamp[qt]=1.e-4
rndz=300.
rndexp=2.

[buffer]
swbuffer=1
zstart=3500.
sigma=0.00223
beta=2.

#[decay]
#swdecay[couvreux]=exponential
#timescale=600.

[time]
endtime=21600
dt=1.
dtmax=60.
savetime=3600
outputiter=1
adaptivestep=true
starttime=0
rkorder=3

[stats]
swstats=1
swtendency=1
sampletime=60
masklist=ql,qlcore
#whitelist=qt_1_qt_1, qt_1_w_1
whitelist=thl_1_qt_1,qt_1_thl_1
#blacklist=.*_w,.*_flux

[column]
swcolumn=0
sampletime=60
coordinates[x]=0, 6400
coordinates[y]=6400, 0

[dump]
swdump=0
sampletime=1800
dumplist=u,v,w,qt,ql,thl

[cross]
swcross=1
crosslist=qt,ql,ql_path,w,u
sampletime=300
xz=6400
yz=6400
xy=5,119

